module Bibframe

	CARRIERS_CODE = {
			"audio cartridge" => "sg",
			"audio cylinder" => "se",
			"audio disc" => "sd",
			"sound track reel" => "si",
			"audio roll" => "sq",
			"audiocassette" => "ss",
			"audiotape reel" => "st",
			"other audio Carrier" => "sz",
			"computer card" => "ck",
			"computer chip cartridge" => "cb",
			"computer disc" => "cd",
			"computer disc cartridge" => "ce",
			"computer tape cartridge" => "ca",
			"computer tape cassette" => "cf",
			"computer tape reel" => "ch",
			"online resource" => "cr",
			"other computer carrier" => "cz",
			"aperture card" => "ha",
			"microfiche" => "he",
			"microfiche cassette" => "hf",
			"microfilm cartridge" => "hb",
			"microfilm cassette" => "hc",
			"microfilm reel" => "hd",
			"microfilm roll" => "hj",
			"microfilm slip" => "hh",
			"microopaque" => "hg",
			"other microform carrier" => "hz",
			"microscope slide" => "pp",
			"other microscopic carrier" => "pz",
			"film cartridge" => "mc",
			"film cassette" => "mf",
			"film reel" => "mr",
			"film roll" => "mo",
			"filmslip" => "gd",
			"filmstrip" => "gf",
			"filmstrip cartridge" => "gc",
			"overhead transparency" => "gt",
			"slide" => "gs",
			"other projected-image carrier" => "mz",
			"stereograph card" => "eh",
			"stereograph disc" => "es",
			"other stereographic Carrier" => "ez",
			"card" => "no",
			"flipchart" => "nn",
			"roll" => "na",
			"sheet" => "nb",
			"volume" => "nc",
			"object" => "nr",
			"other unmediated carrier" => "nz",
			"video cartridge" => "vc",
			"videocassette" => "vf",
			"videodisc" => "vd",
			"videotape reel" => "vr",
			"other video carrier" => "vz",
			"unspecified" => "zu",
		}.freeze

  CLASSES = {
  	"work" => [
		    {name: "classificationNumber", tag: "(050|051|055|060|061|070|071|080|082|083|084|086)", sfcodes: "a"},
		    {name: "classificationSpanEnd", tag: "083", sfcodes: "c"},
		    {name: "classificationTableSeq", tag: "083", sfcodes: "y"},
		    {name: "classificationTable", tag: "083", sfcodes: "z"},
		    {name: "classificationScheme", tag: "086", sfcodes: "2"},
		    {name: "classificationEdition", tag: "(080|082|083)", ind1: "1"},
		    {name: "classificationEdition", tag: "080|082|083", ind1: "0"},
		    {name: "classificationAssigner", tag: "(050|051|060|061|070|071|082|083|084)"},

		    {name: "classificationDesignation", tag: "(082|083)" , sfcodes: "m=a then'standard', m=b then 'optional'"},
		    {name: "classificationStatus", tag: "if " , sfcodes: "z then status=canceled/invalid"},
		    {name: "classificationLcc", tag: "(050|051|052|055|070|071)", sfcodes: "a", level: "property"},
		    {name: "classificationNlm", tag: "(060|061)", sfcodes: "a", level: "property"},
		    {name: "classification", tag: "(084|086)", ind1: " ", sfcodes: "a", level: "property"},
		    {name: "classificationDdc", tag: "083", sfcodes: "a'hyphen'c", level: "property"},
		    {name: "classificationDdc", tag: "082", sfcodes: "a", level: "property"},
		    {name: "classificationUdc", tag: "080", sfcodes: "a+c", level: "property"},
  		],
  		"Holding" => [
    			{name: "classificationItem", tag: "(050|051|055|060|061|070|071|080|082|083|084|086)", sfcodes: "b"},
    	]
  }.freeze


	CONTENT_TYPES_CODE = {
		"cartographic dataset" => "crd",
		"cartographic image" => "cri",
		"cartographic moving image" => "crm",
		"cartographic tactile image" => "crt",
		"cartographic tactile three-dimensional form" => "crn",
		"cartographic three-dimensional form" => "crf",
		"computer dataset" => "cod",
		"computer program" => "cop",
		"notated movement" => "ntv",
		"notated music" => "ntm",
		"performed music" => "prm",
		"sounds" => "snd",
		"spoken word" => "spw",
		"still image" => "sti",
		"tactile image" => "tci",
		"tactile notated music" => "tcm",
		"tactile notated movement" => "tcn",
		"tactile text" => "tct",
		"tactile three-dimensional form" => "tcf",
		"text" => "txt",
		"three-dimensional form" => "tdf",
		"three-dimensional moving image" => "tdm",
		"two-dimensional moving image" => "tdi",
		"other" => "xxx",
		"unspecified" => "zzz",
	}.freeze

  FORMS_OF_ITEMS = {
	  "a" => {form: "Microfilm", rtype: %w(Text Book NotatedMusic MusicRecording MixedMaterial)},
	  "b" => {form: "Microfiche", rtype: %w(Text Book NotatedMusic MusicRecording MixedMaterial)},
	  "c" => {form: "Microopaque", rtype: %w(Text Book NotatedMusic MusicRecording MixedMaterial)},
	  "d" => {form: "Large print", rtype: %w(Text Book NotatedMusic MusicRecording MixedMaterial)},
	  "f" => {form: "Braille", rtype: %w(Text Book NotatedMusic MusicRecording MixedMaterial)},
	  "o" => {form: "Online", rtype: %w(Text Book NotatedMusic MusicRecording MixedMaterial SoftwareApplication)},
	  "q" => {form: "Direct electronic", rtype: %w(Text Book NotatedMusic MusicRecording MixedMaterial SoftwareApplication)},
	  "r" => {form: "Regular print reproduction", rtype: %w(Text Book NotatedMusic MusicRecording MixedMaterial)},
	  "s" => {form: "Electronic", rtype: %w(Text Book NotatedMusic MusicRecording MixedMaterial)},
  }.freeze

  I2I_TARGET_TAGS = %w(776 530).freeze

	I2I_RERATIONS = [
	 {tag: "776", property: "otherPhysicalFormat", reverse: "hasOtherPhysicalFormat"}
	].freeze

	INSTANCE_TYPES = {
		'cf007' => {
			"c" => "Electronic",
			"f" => "Tactile",
		},
		'leader6' => {
			"d" => "Manuscript",
			"f" => "Manuscript",
			"t" => "Manuscript",
		},
		'leader7' => {
			"b" => "Serial",
			"c" => "Collection",
			"d" => "Collection",
			"i" => "Integrating",
			"s" => "Serial",
		},
		'leader8' => {
			"a" => "Archival",
		},
		'sf336a' => {
			"tactile text" => "Tactile",
		},
		'sf336b' => {
			"tct" => "Tactile",
		},
	}.freeze

	MEDIA_TYPES_CODE = {
	  "audio"         => "s",
	  "computer"      => "c",
	  "microform"     => "h",
	  "microscopic"   => "p",
	  "projected"     => "g",
	  "stereographic" => "e",
	  "unmediated"    => "n",
	  "video"         => "v",
	  "other"         => "x",
	  "unspecified"   => "z",
	}.freeze

	RELATIONSHIPS = {
		'work' => [
			{tag: "(700|710|711|720)", ind2: "2", property: "hasPart"},
			{tag: "(700|710|711|720)", ind2: "( |0|1)", property: "relatedResource"},
			{tag: "740", ind2: " ", property: "relatedWork"},
			{tag: "740", property: "partOf", ind2: "2"},
			{tag: "760", property: "subseriesOf"},
			{tag: "762", property: "subseries"},
			{tag: "765", property: "translationOf"},
			{tag: "767", property: "translation"},
			{tag: "770", property: "supplement"},
			{tag: "772", ind2: " ", property: "supplementTo"},
			{tag: "773", property: "partOf"},
			{tag: "774", property: "hasPart"},
			{tag: "775", property: "otherEdition" },
			{tag: "777", property: "issuedWith"},
			{tag: "780", ind2: "0", property: "continues"},
			{tag: "780", ind2: "1", property: "continuesInPart"},
			{tag: "780", ind2: "2", property: "supersedes"},
			{tag: "780", ind2: "3", property: "supersedesInPartBy"},
			{tag: "780", ind2: "4", property: "unionOf"},
			{tag: "780", ind2: "5", property: "absorbed"},
			{tag: "780", ind2: "6", property: "absorbedInPartBy"},
			{tag: "780", ind2: "7", property: "separatedFrom"},
			{tag: "785", ind2: "0" , property: "continuedBy"},
			{tag: "785", ind2: "1", property: "continuedInPartBy"},
			{tag: "785", ind2: "2" , property: "supersededBy"},
			{tag: "785", ind2: "3", property: "supersededInPartBy"},
			{tag: "785", ind2: "4", property: "absorbedBy"},
			{tag: "785", ind2: "5" , property: "absorbedInPartBy"},
			{tag: "785", ind2: "6" , property: "splitInto"},
			{tag: "785", ind2: "7" , property: "mergedToForm"},
			{tag: "785", ind2: "8" , property: "continuedBy"},
			{tag: "786", property: "dataSource"},
			{tag: "533", property: "reproduction"},
			{tag: "534", property: "originalVersion"},
			{tag: "787", property: "relatedResource"},
			{tag: "630" , property: "subject"},
			{tag: "(400|410|411|430|440|490|800|810|811|830)", property: "series"},
			{tag: "730", property: "relatedWork" , ind2: " "},
			{tag: "730", property: "hasPart", ind2: "2" },
		],
		'instance' => [
			],
	}.freeze

	RESOURCE_TYPES = {
    :leader => {
      "a" => "Text",
      "c" => "NotatedMusic",
      "d" => "NotatedMusic",
      "e" => "Cartography",
      "f" => "Cartography",
      "g" => "MovingImage",
      "i" => "Audio",
      "j" => "Audio",
      "k" => "StillImage",
      "m" => "Dataset",
      "m" => "Multimedia",
      "o" => "MixedMaterial",
      "p" => "MixedMaterial",
      "r" => "ThreeDimensionalObject",
      "t" => "Text",
    },
    :cf007 => {
      "a" => "Cartography",
      "d" => "Cartography",
      "f" => "Tactile",
      "m" => "MovingImage",
      "o" => "MixedMaterial",
      "q" => "NotatedMusic",
      "r" => "Cartography",
      "s" => "Audio",
      "t" => "Text",
      "v" => "MovingImage",
    },
    :sf336a => {
      "cartographic dataset" => ["Cartography", "Dataset"],
      "cartographic image" => ["Cartography", "StillImage"],
      "cartographic moving image" => ["Cartography", "MovingImage"],
      "cartographic tactile image" => ["Cartography", "Dataset"],
      "cartographic tactile three dimensional form" => ["Cartography", "Dataset", "ThreeDimensionalObject"],
      "cartographic three dimensional form" => ["Cartography", "ThreeDimensionalObject"],
      "computer dataset" => ["Dataset"],
      "computer program" => ["Multimedia"],
      "notated movement" => ["NotatedMovement"],
      "notated music" => ["NotatedMusic"],
      "performed music" => ["Audio"],
      "sounds" => ["Audio"],
      "spoken word" => ["Audio"],
      "still image" => ["StillImage"],
      "tactile image" => ["Dataset", "StillImage"],
      "tactile notated movement" => ["Dataset", "NotatedMovement"],
      "tactile notated music" => ["Dataset"],
      "tactile notated music" => ["NotatedMusic"],
      "tactile text" => ["Dataset", "Text"],
      "tactile three-dimensional form" => ["Dataset", "ThreeDimensionalObject"],
      "text" => ["Text"],
      "three-dimensional form" => ["ThreeDimensionalObject"],
      "three-dimensional moving image" => ["MovingImage", "ThreeDimensionalObject"],
      "two-dimensional moving image" => ["MovingImage"],
    },
    :sf336b => {
      "ccm" => ["NotatedMusic"],
      "cod" => ["Ddataset"],
      "cop" => ["Multimedia"],
      "crd" => ["Cartography", "Ddataset"],
      "crf" => ["Cartography", "ThreeDimensionalObject"],
      "cri" => ["Cartography", "StillImage"],
      "crm" => ["Cartography"],
      "crn" => ["Cartography", "Dataset", "ThreeDimensionalObject"],
      "crt" => ["Cartography", "Dataset"],
      "ntm" => ["NotatedMusic"],
      "ntv" => ["NotatedMovement"],
      "prm" => ["Audio"],
      "snd" => ["Audio"],
      "spw" => ["Audio"],
      "sti" => ["StillImage"],
      "tcf" => ["Dataset", "ThreeDimensionalObject"],
      "tci" => ["Dataset", "StillImage"],
      "tcm" => ["Dataset", "ThreeDimensionalObject"],
      "tcn" => ["Dataset", "NotatedMovement"],
      "tct" => ["Dataset", "Text"],
      "tdf" => ["ThreeDimensionalObject"],
      "tdi" => ["MovingImage"],
      "tdm" => ["MovingImage"],
      "txt" => ["Text"],
    },
    :sf337a => {
      "audio" => "Audio",
    },
    :sf337b => {
      "s" => "Audio",
    }
  }.freeze

  SIMPLE_PROPERTIES = {
    "annotation" => [
      {property: "descriptionConventions", tag: "040", sfcodes: "e", uri: "http://id.loc.gov/vocabulary/descriptionConventions/"},
      {property: "descriptionLanguage", tag: "040", sfcodes: "b", uri: "http://id.loc.gov/vocabulary/languages/"},
      {property: "descriptionSource", tag: "040", sfcodes: "a", uri: "http://id.loc.gov/vocabulary/organizations/", group: "identifiers"},
    ],
    "arrangement" => [
      {property: "materialArrangement", tag: "351", sfcodes: "b"},
      {property: "materialArrangement", tag: "351", sfcodes: "b"},
      {property: "materialHierarchicalLevel", tag: "351", sfcodes: "c"},
      {property: "materialOrganization", tag: "351", sfcodes: "a"},
      {property: "materialPart", tag: "351", sfcodes: "3"},
    ],
    "cartography" => [
      {property: "cartographicAscensionAndDeclination", tag: "255", sfcodes: "d"},
      {property: "cartographicCoordinates", tag: "255", sfcodes: "c"},
      {property: "cartographicEquinox", tag: "255", sfcodes: "e"},
      {property: "cartographicExclusionGRing", tag: "255", sfcodes: "g"},
      {property: "cartographicOuterGRing", tag: "255", sfcodes: "f"},
      {property: "cartographicProjection", tag: "255", sfcodes: "b"},
      {property: "cartographicScale", tag: "034", sfcodes: ""},
      {property: "cartographicScale", tag: "255", sfcodes: "a"},
    ],
    "classification" => [
      {property: "classificationAssigner", tag: "083", sfcodes: ""},
      {property: "classificationEdition", tag: "082", sfcodes: ""},
      {property: "classificationEdition", tag: "083", sfcodes: ""},
      {property: "classificationSpanEnd", tag: "083", sfcodes: "c"},
      {property: "classificationTable", tag: "083", sfcodes: "z"},
      {property: "classificationTableSeq", tag: "083", sfcodes: "y"},
    ],
    "contentcategory" => [
      {property: "contentCategory", tag: "130", sfcodes: "h"},
      {property: "contentCategory", tag: "240", sfcodes: "h"},
      {property: "contentCategory", tag: "243", sfcodes: "h"},
      {property: "contentCategory", tag: "245", sfcodes: "k"},
      {property: "contentCategory", tag: "513", sfcodes: "a"},
      {property: "contentCategory", tag: "516", sfcodes: "a"},
      {property: "contentCategory", tag: "700", sfcodes: "h"},
      {property: "contentCategory", tag: "710", sfcodes: "h"},
      {property: "contentCategory", tag: "711", sfcodes: "h"},
      {property: "contentCategory", tag: "730", sfcodes: "h"},
    ],
    "event" => [
      {property: "eventDate", tag: "518", sfcodes: "d"},
    ],
    "findingAid" => [
      {property: "findingAidNote", tag: "555", sfcodes: "3abc"},
    ],
    "helditem" => [
       {property: "custodialHistory", tag: "561", sfcodes: "a"},
    ],
    "instance" => [
      {property: "$2", tag: "024", sfcodes: "a", ind1: "7", group: "identifiers"},
      {property: "accessCondition", tag: "506"},
      {property: "aspectRatio", tag: "345", sfcodes: "a"},
      {property: "coden", tag: "030", sfcodes: "a", group: "identifiers"},
      {property: "contentsNote", tag: "505", sfcodes: "agrtu", ind2: " "},
      {property: "copyrightDate", tag: "264", sfcodes: "c", ind2: "4"},
      {property: "creditsNote", tag: "508", startwith: "Credits: "},
      {property: "dimensions", tag: "300", sfcodes: "c"},
      {property: "ean", tag: "024", sfcodes: "a,z,d", ind1: "3", group: "identifiers", comment: "(sep by -)"},
      {property: "edition", tag: "250", sfcodes: "a"},
      {property: "editionResponsibility", tag: "250", sfcodes: "b"},
      {property: "extent", tag: "300", sfcodes: "af"},
      {property: "fingerprint", tag: "026", sfcodes: "e", group: "identifiers"},
      {property: "formDesignation", tag: "245", sfcodes: "h"},
      {property: "formDesignation", tag: "245", sfcodes: "k"},
      {property: "graphicScaleNote", tag: "507", sfcodes: "a"},
      {property: "illustrationNote", tag: "300", sfcodes: "b"},
      {property: "immediateAcquisition", tag: "541", sfcodes: "cad"},
      {property: "ismn", tag: "024", sfcodes: "a", ind1: "2", group: "identifiers"},
      {property: "isrc", tag: "024", sfcodes: "a", ind1: "0", group: "identifiers"},
      {property: "issn", tag: "022", sfcodes: "a", group: "identifiers", uri: "http://issn.example.org/"},
      {property: "languageNote", tag: "546", sfcodes: "3a"},
      {property: "lccn", tag: "010", sfcodes: "a", uri: "http://id.loc.gov/authorities/test/identifiers/lccn/", group: "identifiers"},
      {property: "lcOverseasAcq", tag: "025", sfcodes: "a", group: "identifiers"},
      {property: "legalDeposit", tag: "017", sfcodes: "a", group: "identifiers"},
      {property: "matrixNumber", tag: "028", sfcodes: "a", ind1: "1", group: "identifiers"},
      {property: "musicPlate", tag: "028", sfcodes: "a", ind1: "2", group: "identifiers"},
      {property: "musicPublisherNumber", tag: "028", sfcodes: "a", ind1: "3", group: "identifiers"},
      {property: "nban", tag: "016", sfcodes: "a", group: "identifiers"},
      {property: "nbn", tag: "015", sfcodes: "a", group: "identifiers"},
      {property: "notation", tag: "546", sfcodes: "b"},
      {property: "note", tag: "500", sfcodes: "3a"},
      {property: "performerNote", tag: "511", startwith: "Cast: "},
      {property: "philatelicDataNote", tag: "258", sfcodes: "ab"},
      {property: "postalRegistration", tag: "032", sfcodes: "a", group: "identifiers"},
      {property: "preferredCitation", tag: "524"},
      {property: "providerStatement", tag: "260", sfcodes: "abc"},
      {property: "publisherNumber", tag: "028", sfcodes: "a", ind1: "5", group: "identifiers"},
      {property: "reportNumber", tag: "088", sfcodes: "a", group: "identifiers"},
      {property: "responsibilityStatement", tag: "245", sfcodes: "c"},
      {property: "sici", tag: "024", sfcodes: "a", ind1: "4", group: "identifiers"},
      {property: "stockNumber", tag: "037", sfcodes: "a", group: "identifiers"},
      {property: "strn", tag: "027", sfcodes: "a", group: "identifiers"},
      {property: "studyNumber", tag: "036", sfcodes: "a", group: "identifiers"},
      {property: "systemNumber", tag: "035", sfcodes: "a", group: "identifiers", uri: "http://www.worldcat.org/oclc/"},
      {property: "titleStatement", tag: "245", sfcodes: "ab"},
      {property: "upc", tag: "024", sfcodes: "a", ind1: "1", group: "identifiers"},
      {property: "videorecordingNumber", tag: "028", sfcodes: "a", ind1: "4", group: "identifiers"},
    ],
    "specialinstnc" => [
      {property: "carrierCategory", tag: "338", sfcodes: "a", uri: "http://id.loc.gov/vocabulary/carriers/"},
      {property: "carrierCategory", tag: "338", sfcodes: "b", uri: "http://id.loc.gov/vocabulary/carriers/"},
      {property: "mediaCategory", tag: "337", sfcodes: "a", uri: "http://id.loc.gov/vocabulary/mediaCategory/"},
      {property: "mediaCategory", tag: "337", sfcodes: "b", uri: "http://id.loc.gov/vocabulary/mediaCategory/"},
    ],
    "title" => [
      {property: "partNumber", tag: "130", sfcodes: "n"},
      {property: "partNumber", tag: "240", sfcodes: "n"},
      {property: "partNumber", tag: "245", sfcodes: "n"},
      {property: "partNumber", tag: "246", sfcodes: "n"},
      {property: "partNumber", tag: "247", sfcodes: "n"},
      {property: "partTitle", tag: "130", sfcodes: "p"},
      {property: "partTitle", tag: "240", sfcodes: "p"},
      {property: "partTitle", tag: "242", sfcodes: "p"},
      {property: "partTitle", tag: "245", sfcodes: "p"},
      {property: "partTitle", tag: "246", sfcodes: "p"},
      {property: "partTitle", tag: "247", sfcodes: "p"},
      {property: "partTitle", tag: "730", sfcodes: "p"},
      {property: "subtitle", tag: "245", sfcodes: "b"},
      {property: "subtitle", tag: "246", sfcodes: "b"},
      {property: "subtitle", tag: "247", sfcodes: "b"},
      {property: "titleAttribute", tag: "130", sfcodes: "g"},
      {property: "titleAttribute", tag: "240", sfcodes: "g"},
      {property: "titleAttribute", tag: "240", sfcodes: "o"},
      {property: "titleQualifier", tag: "210", sfcodes: "b"},
      {property: "titleQualifier", tag: "222", sfcodes: "b"},
      {property: "titleSource", tag: "210", sfcodes: "2"},
      {property: "titleValue", tag: "130", sfcodes: "a"},
      {property: "titleValue", tag: "210", sfcodes: "a"},
      {property: "titleValue", tag: "222", sfcodes: "a"},
      {property: "titleValue", tag: "240", sfcodes: "a"},
      {property: "titleValue", tag: "242", sfcodes: "a"},
      {property: "titleValue", tag: "245", sfcodes: "a"},
      {property: "titleValue", tag: "246", sfcodes: "a"},
      {property: "titleValue", tag: "247", sfcodes: "a"},
      {property: "titleVariationDate", tag: "246", sfcodes: "f"},
      {property: "titleVariationDate", tag: "247", sfcodes: "f"},
    ],
    "work" => [
      {property: "awardNote", tag: "586", sfcodes: "3a"},
      {property: "dissertationDegree", tag: "502", sfcodes: "b"},
      {property: "dissertationNote", tag: "502", sfcodes: "a"},
      {property: "dissertationYear", tag: "502", sfcodes: "d"},
      {property: "duration", tag: "306", sfcodes: "a"},
      {property: "formDesignation", tag: "130", sfcodes: "k"},
      {property: "formDesignation", tag: "240", sfcodes: "k"},
      {property: "formDesignation", tag: "730", sfcodes: "k"},
      {property: "frequencyNote", tag: "310", sfcodes: "ab"},
      {property: "frequencyNote", tag: "321", sfcodes: "ab"},
      {property: "geographicCoverageNote", tag: "522"},
      {property: "issnL", tag: "022", sfcodes: "l", group: "identifiers", uri: "http://issn.example.org/"},
      {property: "legalDate", tag: "130", sfcodes: "d"},
      {property: "legalDate", tag: "730", sfcodes: "d"},
      {property: "musicKey", tag: "130", sfcodes: "r"},
      {property: "musicKey", tag: "240", sfcodes: "r"},
      {property: "musicKey", tag: "384", sfcodes: "a"},
      {property: "musicMediumNote", tag: "130", sfcodes: "m"},
      {property: "musicMediumNote", tag: "240", sfcodes: "m"},
      {property: "musicMediumNote", tag: "243", sfcodes: "m"},
      {property: "musicMediumNote", tag: "382", sfcodes: "adp"},
      {property: "musicMediumNote", tag: "730", sfcodes: "m"},
      {property: "musicNumber", tag: "130", sfcodes: "n"},
      {property: "musicNumber", tag: "730", sfcodes: "n"},
      {property: "musicVersion", tag: "130", sfcodes: "o"},
      {property: "musicVersion", tag: "130", sfcodes: "s"},
      {property: "musicVersion", tag: "240", sfcodes: "o"},
      {property: "musicVersion", tag: "240", sfcodes: "s"},
      {property: "note", tag: "500", sfcodes: "3a"},
      {property: "originDate", tag: "046", sfcodes: "kl", stringjoin: "-"},
      {property: "originDate", tag: "130", sfcodes: "f"},
      {property: "originDate", tag: "130", sfcodes: "f"},
      {property: "originDate", tag: "730", sfcodes: "f"},
      {property: "supplementaryContentNote", tag: "525", sfcodes: "a"},
      {property: "temporalCoverageNote", tag: "513", sfcodes: "b"},
      {property: "treatySignator", tag: "710", sfcodes: "g"},
    ]
  }.freeze

	SUBJECTS_TYPES = {
  	"600" => "Person",
		"610" => "Organization",
		"611" => "Meeting",
		"648" => "Temporal",
		"650" => "Topic",
		"651" => "Place",
		"654" => "Topic",
		"655" => "Topic",
		"656" => "Topic",
		"657" => "Topic",
		"658" => "Topic",
		"662" => "Place",
		"653" => "Topic",
		"751" => "Place",
		"752" => "Topic",
  }

	TARGET_AUDIENCES = {
    "a" => "Pre",
    "b" => "Pri",
    "c" => "Pra",
    "d" => "Ado",
    "e" => "Adu",
    "f" => "Spe",
    "g" => "Gen",
    "j" => "Juv",
  }.freeze

	VALID_LCC = [
		"DAW","DJK","KBM","KBP","KBR","KBU","KDC","KDE","KDG","KDK","KDZ","KEA","KEB",
		"KEM","KEN","KEO","KEP","KEQ","KES","KEY","KEZ","KFA","KFC","KFD","KFF","KFG",
		"KFH","KFI","KFK","KFL","KFM","KFN","KFO","KFP","KFR","KFS","KFT","KFU","KFV",
		"KFW","KFX","KFZ","KGA","KGB","KGC","KGD","KGE","KGF","KGG","KGH","KGJ","KGK",
		"KGL","KGM","KGN","KGP","KGQ","KGR","KGS","KGT","KGU","KGV","KGW","KGX","KGY",
		"KGZ","KHA","KHC","KHD","KHF","KHH","KHK","KHL","KHM","KHN","KHP","KHQ","KHS",
		"KHU","KHW","KJA","KJC","KJE","KJG","KJH","KJJ","KJK","KJM","KJN","KJP","KJR",
		"KJS","KJT","KJV","KJW","KKA","KKB","KKC","KKE","KKF","KKG","KKH","KKI","KKJ",
		"KKK","KKL","KKM","KKN","KKP","KKQ","KKR","KKS","KKT","KKV","KKW","KKX","KKY",
		"KKZ","KLA","KLB","KLD","KLE","KLF","KLH","KLM","KLN","KLP","KLQ","KLR","KLS",
		"KLT","KLV","KLW","KMC","KME","KMF","KMG","KMH","KMJ","KMK","KML","KMM","KMN",
		"KMP","KMQ","KMS","KMT","KMU","KMV","KMX","KMY","KNC","KNE","KNF","KNG","KNH",
		"KNK","KNL","KNM","KNN","KNP","KNQ","KNR","KNS","KNT","KNU","KNV","KNW","KNX",
		"KNY","KPA","KPC","KPE","KPF","KPG","KPH","KPJ","KPK","KPL","KPM","KPP","KPS",
		"KPT","KPV","KPW","KQC","KQE","KQG","KQH","KQJ","KQK","KQM","KQP","KQT","KQV",
		"KQW","KQX","KRB","KRC","KRE","KRG","KRK","KRL","KRM","KRN","KRP","KRR","KRS",
		"KRU","KRV","KRW","KRX","KRY","KSA","KSC","KSE","KSG","KSH","KSK","KSL","KSN",
		"KSP","KSR","KSS","KST","KSU","KSV","KSW","KSX","KSY","KSZ","KTA","KTC","KTD",
		"KTE","KTF","KTG","KTH","KTJ","KTK","KTL","KTN","KTQ","KTR","KTT","KTU","KTV",
		"KTW","KTX","KTY","KTZ","KUA","KUB","KUC","KUD","KUE","KUF","KUG","KUH","KUN",
		"KUQ","KVB","KVC","KVE","KVH","KVL","KVM","KVN","KVP","KVQ","KVR","KVS","KVU",
		"KVW","KWA","KWC","KWE","KWG","KWH","KWL","KWP","KWQ","KWR","KWT","KWW","KWX",
		"KZA","KZD","AC","AE","AG","AI","AM","AN","AP","AS","AY","AZ","BC","BD","BF",
		"BH","BJ","BL","BM","BP","BQ","BR","BS","BT","BV","BX","CB","CC","CD","CE","CJ",
		"CN","CR","CS","CT","DA","DB","DC","DD","DE","DF","DG","DH","DJ","DK","DL","DP",
		"DQ","DR","DS","DT","DU","DX","GA","GB","GC","GE","GF","GN","GR","GT","GV","HA",
		"HB","HC","HD","HE","HF","HG","HJ","HM","HN","HQ","HS","HT","HV","HX","JA","JC",
		"JF","JJ","JK","JL","JN","JQ","JS","JV","JX","JZ","KB","KD","KE","KF","KG","KH",
		"KJ","KK","KL","KM","KN","KP","KQ","KR","KS","KT","KU","KV","KW","KZ","LA","LB",
		"LC","LD","LE","LF","LG","LH","LJ","LT","ML","MT","NA","NB","NC","ND","NE","NK",
		"NX","PA","PB","PC","PD","PE","PF","PG","PH","PJ","PK","PL","PM","PN","PQ","PR",
		"PS","PT","PZ","QA","QB","QC","QD","QE","QH","QK","QL","QM","QP","QR","RA","RB",
		"RC","RD","RE","RF","RG","RJ","RK","RL","RM","RS","RT","RV","RX","RZ","SB","SD",
		"SF","SH","SK","TA","TC","TD","TE","TF","TG","TH","TJ","TK","TL","TN","TP","TR",
		"TS","TT","TX","UA","UB","UC","UD","UE","UF","UG","UH","VA","VB","VC","VD","VE",
		"VF","VG","VK","VM","ZA","A","B","C","D","E","F","G","H","J","K","L","M","N",
		"P","Q","R","S","T","U","V","Z"].freeze

	W2W_TARGET_TAGS = %w(400 410 411 430 440 490 510 533 534 630 700 710 711 720 730 740 760 762 765 767 770 772 773 774 775 777 780 785 787 800 810 811 830).freeze

	W2W_RERATIONS = [
	 {tag: "700|710|711|720", ind2: "2", property: "hasPart", reverse: "isIncludedIn"},
	 {tag: "700|710|711|720", ind2: " |0|1", property: "relatedResource", reverse: "relatedWork"},
	 {tag: "740", ind2: " ", property: "relatedWork", reverse: "relatedWork"},
	 {tag: "740", property: "partOf", ind2: "2", reverse: "hasPart"},
	 {tag: "760", property: "subseriesOf", reverse: "hasParts"},
	 {tag: "762", property: "subseries", reverse: "hasParts"},
	 {tag: "765", property: "translationOf", reverse: "hasTranslation"},
	 {tag: "767", property: "translation", reverse: "translationOf"},
	 {tag: "770", property: "supplement", reverse: "supplement"},
	 {tag: "772", ind2: " ", property: "supplementTo", reverse: "isSupplemented"},
	 {tag: "773", property: "partOf", reverse: "hasConstituent"},
	 {tag: "774", property: "hasPart", reverse: "has Part"},
	 {tag: "775", property: "otherEdition" , reverse: "hasOtherEdition"},
	 {tag: "777", property: "issuedWith", reverse: "issuedWith"},
	 {tag: "780", ind2: "0", property: "continues", reverse: "continuationOf"},
	 {tag: "780", ind2: "1", property: "continuesInPart", reverse: "partiallyContinuedBy"},
	 {tag: "780", ind2: "2", property: "supersedes", reverse: "continuationOf"},
	 {tag: "780", ind2: "3", property: "supersedesInPartBy", reverse: "partiallyContinuedBy"},
	 {tag: "780", ind2: "4", property: "unionOf", reverse: "preceding"},
	 {tag: "780", ind2: "5", property: "absorbed", reverse: "isAbsorbedBy"},
	 {tag: "780", ind2: "6", property: "absorbedInPartBy", reverse: "isPartlyAbsorbedBy"},
	 {tag: "780", ind2: "7", property: "separatedFrom", reverse: "formerlyIncluded"},
	 {tag: "785", ind2: "0", property: "continuedBy", reverse: "continues"},
	 {tag: "785", ind2: "1", property: "continuedInPartBy", reverse: "partiallyContinues"},
	 {tag: "785", ind2: "2", property: "supersededBy", reverse: "continues"},
	 {tag: "785", ind2: "3", property: "supersededInPartBy", reverse: "partiallyContinues"},
	 {tag: "785", ind2: "4", property: "absorbedBy", reverse: "absorbs"},
	 {tag: "785", ind2: "5", property: "absorbedInPartBy", reverse: "partiallyAbsorbs"},
	 {tag: "785", ind2: "6", property: "splitInto", reverse: "splitFrom"},
	 {tag: "785", ind2: "7", property: "mergedToForm", reverse: "mergedFrom"},
	 {tag: "785", ind2: "8", property: "continuedBy", reverse: "formerlyNamed"},
	 {tag: "786", property: "dataSource", reverse: ""},
	 {tag: "533", property: "reproduction", reverse: ""},
	 {tag: "534", property: "originalVersion", reverse: ""},
	 {tag: "787", property: "relatedResource", reverse: "relatedItem"},
	 {tag: "630", property: "subject", reverse: "isSubjectOf"},
	 {tag: "400|410|411|430|440|490|800|810|811|830", property: "series", reverse: "hasParts"},
	 {tag: "730", property: "relatedWork", ind2: " ", reverse: "relatedItem"},
	 {tag: "730", property: "hasPart", ind2: "2" , reverse: "partOf"},
	].freeze

end